### ISSUE TITLE
WriteApi#flush fails too quickly withRetryBuffer

### ISSUE THREAD

**Issue by vikaspotluri123** [influxdata/influxdb-client-js#1017]
### Specifications

* Client Version: 1.33.2
* InfluxDB Version: N/A
* Platform: N/A

On clients with an unhealthy network[^1], my assumption is that `writeApi.flush(true)` will wait for the retry timer to exhaust before rejecting the promise. The current behavior rejects the promise after the first write failure.

[^1]: Simulated by shutting down the Influx server

### Code sample to reproduce problem

```javascript
await writeApi.flush(true)
```

This is the effective code snippet in context:

```js
async function shutdown() {
		// `writeFailed` persists the failed lines to disk for later recovery
		await writeApi.flush().catch(error => logger?.error(error));
		const unsavedCount = writeApi.dispose();
		if (unsavedCount > 0) {
			logger.warn(`${unsavedCount} point(s) were not persisted to influx`);
		}
}
```

### Expected behavior

```bash
> node reproduce.js 2>&1 | grep Write
Write to InfluxDB failed (attempt: 1). Error: connect ECONNREFUSED 127.0.0.1:8086
Write to InfluxDB failed (attempt: 2). Error: connect ECONNREFUSED 127.0.0.1:8086
Write to InfluxDB failed (attempt: 3). Error: connect ECONNREFUSED 127.0.0.1:8086
Write to InfluxDB failed (attempt: 4). Error: connect ECONNREFUSED 127.0.0.1:8086
Write to InfluxDB failed (attempt: 5). Error: connect ECONNREFUSED 127.0.0.1:8086
Write to InfluxDB failed (attempt: 6). Error: Max retry time exceeded.
```

### Actual behavior

```bash
> node reproduce.js 2>&1 | grep Write
Write to InfluxDB failed (attempt: 1). Error: connect ECONNREFUSED 127.0.0.1:8086
```

**Comment by bednar** [comment]
Hi @vikaspotluri123,

Thank you for using our client. I appreciate your interest in understanding its functionalities, particularly regarding error handling and retry strategies.

Our client by default retries requests on specific errors to ensure robustness and reliability. These retries are triggered for `AbortError`, `RequestTimedOutError`, and `HttpError` with specific status codes, which include 404, 408, 425, 429, 500, 502, 503, and 504. This approach helps in handling intermittent issues and network fluctuations effectively.

If your use case requires a different retry strategy, you can customize this behavior using the `writeFailed` callback. This allows you to define custom logic for when and how retries should be executed based on the error encountered.

For more detailed information on how to configure this and to understand the rationale behind our default retry strategy, please refer to these resources:
- [PR #421 on GitHub](https://github.com/influxdata/influxdb-client-js/pull/421) for implementation details.
- [Issue #420 on GitHub](https://github.com/influxdata/influxdb-client-js/issues/420) for a discussion on retry strategies and error handling.

These links will provide you with a deeper insight into the capabilities of our client and how you can tailor it to meet your specific needs.

Best Regards

**Comment by vikaspotluri123** [comment]
Hi @bednar, thanks for the quick response!

I think we're aligned on the expected behavior here 😀

However, I think the SDK is not behaving like the referenced issue. For example, I created a quick HTTP server that allows no requests:

```javascript
Bun.serve({
	port: 8086,
	fetch: () => new Response('Too many requests!', {status: 429}),
});
```

And ran something like this (simplified as a minimum viable reproduction):

```js
const influxSdk = require('@influxdata/influxdb-client');

// declare const persistFailedLines: (lines: string[]) => void
// declare const data: influxSdk.Point[];
// declare const org: string;
// declare const bucket: string;

const influx = new influxSdk.InfluxDB({
	url: 'http://127.0.0.1:8086',
	token: 'doesnotmatter',
	writeOptions: {
		writeFailed(_error, lines, _attempt, _expires) {
			// As per #420, return undefined to follow the default retry policy
			// Since the server is returning a 429, it should be retried by default
			persistFailedLines(lines);
		},
	},
});
const writeApi = influx.getWriteApi(org, bucket);

writeApi.writePoints(data);

await writeApi.flush().catch((error) => console.log({error}));
```

Expected behavior:

Since the default retry policy is used, `flush()` should wait for the 6 retries, and then throw an error that the max retry time was exceeded.

Output:

```
Write to InfluxDB failed (attempt: 1). m [HttpError]: 429 Too Many Requests : Too many requests!
    at IncomingMessage.<anonymous> ($root/node_modules/@influxdata/influxdb-client/dist/index.js:5:5671)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  statusCode: 429,
  statusMessage: 'Too Many Requests',
  body: 'Too many req',
  contentType: 'text/plain;charset=utf-8',
  _retryAfter: 0
}
{
  error: m [HttpError]: 429 Too Many Requests : Too many requests!
      at IncomingMessage.<anonymous> ($root/node_modules/@influxdata/influxdb-client/dist/index.js:5:5671)
      at IncomingMessage.emit (node:events:531:35)
      at endReadableNT (node:internal/streams/readable:1696:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    statusCode: 429,
    statusMessage: 'Too Many Requests',
    body: 'Too many req',
    contentType: 'text/plain;charset=utf-8',
    _retryAfter: 0
  }
}
```

**Comment by bednar** [comment]
Thanks for the detailed insight. Could you please create a test case in our codebase that will allow us to properly enhance the client? Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

**Comment by vikaspotluri123** [comment]
Sure, I'll see if I can take a look this week!

**Comment by vikaspotluri123** [comment]
I did some analysis on this, and the fix might be a bit more complicated.

Observations:

1. The RetryBuffer is a LinkedList of failed WriteBuffer flushes
2. The batch sender is responsible for detecting expired retries and failing. It feels like the RetryBuffer should own this
3. The request scheduler is decoupled from the source/caller (e.g. the flush fn), which limits the ability for the source to determine when the request settles.

My main question is "what does it mean to flush the retryBuffer"?
  a. Do we need to wait for all of the retries to settle?
  b. Do we try each retry node once?
  c. Something else?
  d. What about in the case of WriteApi#flush? Should new WriteBuffer failures be included in the flush?

**Comment by vikaspotluri123** [comment]
@bednar following up on this!
