### ISSUE TITLE
triggerUncaughtException on timed out request

### ISSUE THREAD

**Issue by wneessen** [influxdata/influxdb-client-js#281]
__Expected Behavior:__

I am using this lib as part of https://github.com/wneessen/websiteBench. Last night I ran into a triggerUncaughtException, when the client tried to write to the influxdb cloud and the requests timed out.

This is the full error:
```
WARN: Write to InfluxDB failed (remaining attempts: 3). [g [Error]: Request timed out]
node:internal/process/promises:218
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[g [Error]: Request timed out]
```

I am writing to influxdb via: "_writeApi.writePoint(dataPoint);" and "._writeApi.flush()".
The flush() call is handled via catch(), so I would assume that if a timeout happens during the flushing/writing, this catch() would handle it properly. Which is not the case.

Here is the full code I am using:
```JavaScript
    private async writePointsV2(dataPoints: Array<nodeInfluxClientObj.IPoint>) {
        this._logObj.debug('[InfluxDB Client v2] Sending data to InfluxDB');
        dataPoints.forEach(curPoint => {
            let dataPoint = new influxDbClientObj.Point(curPoint.measurement);
            for(const tagKey in curPoint.tags) {
                dataPoint.tag(tagKey, curPoint.tags[tagKey]);
            }
            for(const fieldKey in curPoint.fields) {
                if(typeof curPoint.fields[fieldKey] === 'number') {
                    dataPoint.floatField(fieldKey, curPoint.fields[fieldKey]);
                }
                else {
                    dataPoint.stringField(fieldKey, curPoint.fields[fieldKey]);
                }
            }
            this._writeApi.writePoint(dataPoint);
        });
        this._writeApi.flush().catch(errorObj => { throw errorObj });
    }
}
```

__Current Behavior:__

The error is not handled proplerly and the node app crashes with a triggerUncaughtException.

__Possible Solution:__

Properly handle the triggerUncaughtException so that the flush().catch() would handle the exception.

__Steps/Code to Reproduce the Problem:__

__Specifications:__

- Version: 1.7.0
- Platform: Linux

**Comment by sranka** [comment]
Thank you @wneessen for reporting an issue, I am on it shortly.

**Comment by sranka** [comment]
`this._writeApi.writePoint` can actually auto-flush the data when more than [maxBatchSize](https://influxdata.github.io/influxdb-client-js/influxdb-client.writeoptions.html) (1000 by default) points are written or after a minute from the `last write` that was not flushed. It must not, however, exit the node process (triggerUncaughtException). I am trying to write an extra test to reproduce this.

**Comment by sranka** [comment]
I added an extra test to make sure that background flush errors are caught, all tests pass. I went through the code to see that `WARN: Write to InfluxDB failed (remaining attempts: 3). ...` is only printed when the write fails, the associated promise is indeed rejected and propagated to the caller (when `flush` or `close` is called) or silently caught when [batchSize is reached](https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/impl/WriteApiImpl.ts#L38)  or [after a minute with unflushed data](https://github.com/influxdata/influxdb-client-js/blob/2f19d3b319a2305a58fe6d83471b7b70104ae2d6/packages/core/src/impl/WriteApiImpl.ts#L106)

@wneessen Can you please inspect the trace of  `triggerUncaughtException`, it does not seem to originate in this client library. Additionally, if you want to have the data flushed with `this._writeApi.flush()` call, call `flush` also inside your `forEach` loop (right before reaching the batchSize).

**Comment by wneessen** [comment]
Thanks for the help @sranka. I've reproduced the issue by blocking the InfluxDB Cloud IP via iptables. This time with tracing activated. Here is the full trace. I've also moved the flush() statement according to your recommendation into the foreach loop.

```
WARN: Write to InfluxDB failed (remaining attempts: 3). [g [Error]: Request timed out]
node:internal/process/promises:199
        triggerUncaughtException(err, true /* fromPromise */);
        ^

[g [Error]: Request timed out]
Thrown at:
    at g (/home/wneessen/devel/github.com/wneessen/websiteBench/node_modules/@influxdata/influxdb-client/dist/index.js:1:1277)
    at /home/wneessen/devel/github.com/wneessen/websiteBench/node_modules/@influxdata/influxdb-client/dist/index.js:16:9019
    at emit (node:events:327:20)
    at emitRequestTimeout (node:_http_client:796:9)
    at onceWrapper (node:events:433:28)
    at emit (node:events:339:22)
    at Socket._onTimeout (node:net:471:8)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
```

**Comment by sranka** [comment]
Can you please also share your node version?

**Comment by wneessen** [comment]
I am running v15.0.1

**Comment by wneessen** [comment]
I poked around a little bit. Looks like the on('timeout') is causing the problem:
https://github.com/influxdata/influxdb-client-js/blob/a126a0fc97fbc0719552374efcac9dc67734d1c3/packages/core/src/impl/node/NodeHttpTransport.ts#L269

When I put a simple ```return``` into that instead of the ```listeners.error(new RequestTimedOutError())``` it will not throw the triggerUncaughtException anymore. Unfortunately I am not familiar enough with this codebase to get the root cause for that, as the ```listeners.error(new RequestTimedOutError())``` looks valid to me.

**Comment by sranka** [comment]
Yes, it is the place where the error is thrown, it is correct to pass it upwards. I am trying to find a simple standalone example that I could use to reproduce this issue. I tried the following code with 1.8.0 client, still with no success. Can you please try to reproduce this issue with the simple example?

```js
#!/usr/bin/env node
const {InfluxDB, Point} = require('@influxdata/influxdb-client')
// const {InfluxDB, Point} = require('../packages/core')

async function startServer() {
  const http = require('http')

  return new Promise(resolve => {
    const server = http.createServer(function(req, res) {
      setTimeout(function() {
        res.writeHead(200, {'Content-Type': 'text/plain'})
        res.end('Hello I am awake')
      }, 100000) // wait 100 seconds with a reply
    })
    server.listen(3001, () => {
      const url = `http://localhost:${server.address().port}`
      console.log(`Fake server started at: ${url}`)
      resolve(url)
    })
  })
}

async function write(url) {
  // create a write API, expecting point timestamps in nanoseconds (can be also 's', 'ms', 'us')
  const writeApi = new InfluxDB({
    url,
    timeout: 2000, // let it timeout in 2 seconds (10 secs OOTB)
  }).getWriteApi('org', 'bucket', 'ns')
  // write point with the current (client-side) timestamp
  const point1 = new Point('temperature')
    .tag('example', 'write.ts')
    .floatField('value', 20 + Math.round(100 * Math.random()) / 10)
  writeApi.writePoint(point1)
  writeApi.writePoint(point1)
  console.log('WriteApi Flush')
  await writeApi.flush().catch(e => console.error('flushed failed', e))
  // now it should exit
  console.log('WriteApi Close')
  await writeApi.close().catch(console.error)
}

process.on('unhandledRejection', (error, promise) => {
  // !!!THIS shouldn't be even called!!!
  console.log('=== UNHANDLED REJECTION ===')
  console.log('error', error)
  console.log('promise', promise)
})
const pavel = new Error('Pavel')
startServer()
  .then(url => write(url))
  .then(() => Promise.reject(pavel))
```

**Comment by wneessen** [comment]
Here you go:
```
Fake server started at: http://localhost:3001
WriteApi Flush
WARN: Write to InfluxDB failed (remaining attempts: 3). g [Error]: Request timed out
    at ClientRequest.<anonymous> (/home/wneessen/devel/github.com/wneessen/websiteBench/node_modules/@influxdata/influxdb-client/dist/index.js:16:9019)
    at ClientRequest.emit (node:events:327:20)
    at Socket.emitRequestTimeout (node:_http_client:796:9)
    at Object.onceWrapper (node:events:433:28)
    at Socket.emit (node:events:339:22)
    at Socket._onTimeout (node:net:471:8)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
flushed failed g [Error]: Request timed out
    at ClientRequest.<anonymous> (/home/wneessen/devel/github.com/wneessen/websiteBench/node_modules/@influxdata/influxdb-client/dist/index.js:16:9019)
    at ClientRequest.emit (node:events:327:20)
    at Socket.emitRequestTimeout (node:_http_client:796:9)
    at Object.onceWrapper (node:events:433:28)
    at Socket.emit (node:events:339:22)
    at Socket._onTimeout (node:net:471:8)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
WriteApi Close
ERROR: Retry buffer closed with 2 items that were not written to InfluxDB!
/home/wneessen/devel/github.com/wneessen/websiteBench/failtest.js:48
const pavel = new Error('Pavel')
              ^

Error: Pavel
    at Object.<anonymous> (/home/wneessen/devel/github.com/wneessen/websiteBench/failtest.js:48:15)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12)
    at node:internal/main/run_main_module:17:47
Thrown at:
    at /home/wneessen/devel/github.com/wneessen/websiteBench/failtest.js:48:15
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Module._load (node:internal/modules/cjs/loader:789:14)
    at executeUserEntryPoint (node:internal/modules/run_main:72:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by wneessen** [comment]
Sorry, the copy&paste didn't work properly:
```
Fake server started at: http://localhost:3001
WriteApi Flush
WARN: Write to InfluxDB failed (remaining attempts: 3). g [Error]: Request timed out
    at ClientRequest.<anonymous> (/home/wneessen/devel/github.com/wneessen/websiteBench/node_modules/@influxdata/influxdb-client/dist/index.js:16:9019)
    at ClientRequest.emit (node:events:327:20)
    at Socket.emitRequestTimeout (node:_http_client:796:9)
    at Object.onceWrapper (node:events:433:28)
    at Socket.emit (node:events:339:22)
    at Socket._onTimeout (node:net:471:8)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
flushed failed g [Error]: Request timed out
    at ClientRequest.<anonymous> (/home/wneessen/devel/github.com/wneessen/websiteBench/node_modules/@influxdata/influxdb-client/dist/index.js:16:9019)
    at ClientRequest.emit (node:events:327:20)
    at Socket.emitRequestTimeout (node:_http_client:796:9)
    at Object.onceWrapper (node:events:433:28)
    at Socket.emit (node:events:339:22)
    at Socket._onTimeout (node:net:471:8)
    at listOnTimeout (node:internal/timers:555:17)
    at processTimers (node:internal/timers:498:7)
WriteApi Close
ERROR: Retry buffer closed with 2 items that were not written to InfluxDB!
/home/wneessen/devel/github.com/wneessen/websiteBench/failtest.js:48
const pavel = new Error('Pavel')
              ^

Error: Pavel
    at Object.<anonymous> (/home/wneessen/devel/github.com/wneessen/websiteBench/failtest.js:48:15)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12)
    at node:internal/main/run_main_module:17:47
Thrown at:
    at /home/wneessen/devel/github.com/wneessen/websiteBench/failtest.js:48:15
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Module._load (node:internal/modules/cjs/loader:789:14)
    at executeUserEntryPoint (node:internal/modules/run_main:72:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by sranka** [comment]
I also left some code that shouldn't be here (`Error('pavel')`), I also repaired the example. There is however no uncaught exception from influx client to reproduce.

**Comment by wneessen** [comment]
You are right. I changed my code to:
```js
this._writeApi.flush().catch(err => (new Error(err)));
```
And now the warning shows up without breaking the node process
```
2020-11-11 17:20:40.406.000      DEBUG  Performance check completed in 2.813 seconds
WARN: Write to InfluxDB failed (remaining attempts: 3). [g [Error]: Request timed out]
WARN: Write to InfluxDB failed (remaining attempts: 3). [g [Error]: Request timed out]
WARN: Write to InfluxDB failed (remaining attempts: 3). [g [Error]: Request timed out]
```

Sorry for the false alert- I should have caught that. Thanks for your assistance on this issue. Highly appreciated!

**Comment by sranka** [comment]
You are welcome! A final nit:
```
this._writeApi.flush().catch(() => 0)
```
