### ISSUE TITLE
TypeError: this.writeBuffer.flush(...).finally is not a function

### ISSUE THREAD

**Issue by 77schneimi** [influxdata/influxdb-client-js#339]
__Expected Behavior:__
Execute your test script `write.js `.

__Current Behavior:__

When execute get the error:
```sh
/Users/77schneimi/Code/nodeInflux/node_modules/@influxdata/influxdb-client/dist/index.js:16
function Q(t,e,r,s){return new(r||(r=Promise))((function(n,i){function o(t){try{a(s.next(t))}catch(t){i(t)}}function l(t){try{a(s.throw(t))}catch(t){i(t)}}function a(t){var e;t.done?n(t.value):(e=t.value,e instanceof r?e:new r((function(t){t(e)}))).then(o,l)}a((s=s.apply(t,e||[])).next())}))}class tt{constructor(t){this.options=Object.assign(Object.assign({},R),t),this.success()}nextDelay(t,e){const r=m(t);if(r&&r>0)return r+Math.round(Math.random()*this.options.retryJitter);if(e&&e>0){let t=this.options.minRetryDelay;for(let r=1;r<e&&(t*=this.options.exponentialBase,!(t>=this.options.maxRetryDelay));r++);return Math.min(Math.max(t,1),this.options.maxRetryDelay)+Math.round(Math.random()*this.options.retryJitter)}return this.currentDelay?this.currentDelay=Math.min(Math.max(this.currentDelay*this.options.exponentialBase,1)+Math.round(Math.random()*this.options.retryJitter),this.options.maxRetryDelay):this.current

TypeError: this.writeBuffer.flush(...).finally is not a function
    at st.close (/Users/77schneimi/Code/nodeInflux/node_modules/@influxdata/influxdb-client/dist/index.js:16:5545)
    at Object.<anonymous> (/Users/77schneimi/Code/nodeInflux/server.js:44:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```
__Possible Solution:__

don't know? 

__Steps/Code to Reproduce the Problem:__

1. config values in env.js
1. run your example script write.js

__Specifications:__

- Version: 
  - latest (influx-client-js)
  - node v7.4.0
  - npm  v4.0.5
- Platform: apple silicon (M1)

**Comment by sranka** [comment]
@77schneimi pls upgrade to node 10+ that implements the required API https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally . Alternatively, install a polyfill, such as https://github.com/es-shims/Promise.prototype.finally .

**Comment by 77schneimi** [comment]
thanks that's works
