### ISSUE TITLE
writeFailed example

### ISSUE THREAD

**Issue by pbegg** [influxdata/influxdb-client-js#420]
I have been looking at the writeAdvanced example and would like to utilise the writeFailed function.
[writeAdvanced line 54](https://github.com/influxdata/influxdb-client-js/blob/5e6cb4741a6ea77fc48777dc56779cc5b06b9a48/examples/writeAdvanced.js#L54)

I would like to use this to store the failed lines to disc if it reaches the maxRetry amount. This is to be used when there are long periods of no internet coverage on a vessel using a 4G connection. I would then run some additional logic to upload the data when the internet comes back. I am unsure of what structure to follow. As pseudo code i have ->

```
    const url = options["influxHost"]
    const token = options["influxToken"]
    const org = options["influxOrg"]
    const bucket = options["influxBucket"]
    const writeOptions = options["writeOptions"]
    const defaultTags = {}
    const writeApi = new InfluxDB({
    	url,
    	token})
    		.getWriteApi(
    			org,
    			bucket,
    			'ms',
    			writeOptions)

    writeApi.useDefaultTags(defaultTags)

    writeApi.writePoint(influxFormat(seperatePath.path,seperatePath.value,seperatePath.timestamp,options)

```

how would I implement the writeFailed function?

I have tried as follows but I don't know if this is corect?

```
    const url = options["influxHost"]
    const token = options["influxToken"]
    const org = options["influxOrg"]
    const bucket = options["influxBucket"]
    const writeOptions = options["writeOptions"]

    writeOptions.writeFailed = function (error,lines,failedAttempts) {
      app.debug(error,lines,failedAttempts)
    }

    const defaultTags = {}

    const writeApi = new InfluxDB({
    	url,
    	token})
    		.getWriteApi(
    			org,
    			bucket,
    			'ms',
    			writeOptions)

    writeApi.useDefaultTags(defaultTags)

    writeApi.writePoint(influxFormat(seperatePath.path,seperatePath.value,seperatePath.timestamp,options)

```

**Comment by sranka** [comment]
@pbegg [writeFailed](https://influxdata.github.io/influxdb-client-js/influxdb-client.writeretryoptions.writefailed.html) function receives the count of already failed attempts, your writeOptions can then contain :
```js
const MAX_RETRIES = 3
const writeOptions = {
  maxRetries: MAX_RETRIES,
  writeFailed: function(error, lines, failedAttempts){
     if (failedAttempts === MAX_RETRIES) {
          // TODO persist protocol lines so that they can be possibly resent later using writeApi.writeRecords(lines)
          return // let the library log the last failed attempt by returning undefined
     }
     // nothing to do herein, the default retry mechanism will be applied by returning undefined
  },
}
```

FYI: the implementation that reacts upon write failure is in https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/impl/WriteApiImpl.ts#L170-L203

**Comment by pbegg** [comment]
This works great thank you.
When the write fails I still get an error showing:

```
WARN: Write to InfluxDB failed (remaining attempts: 3). { Error: getaddrinfo ENOTFOUND us-west-2-1.aws.cloud2.influxdata.com us-west-2-1.aws.cloud2.influxdata.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'us-west-2-1.aws.cloud2.influxdata.com',
  host: 'us-west-2-1.aws.cloud2.influxdata.com',
  port: 443 }

WARN: Write to InfluxDB failed (remaining attempts: 2). { Error: getaddrinfo ENOTFOUND influxurl influxurl:433
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'hostname',
  host: 'host',
  port: 443 }
```

Where would I be able to control this output and log say the code or errno?

**Comment by pbegg** [comment]
This works great thank you.
When the write fails I still get an error showing:

```
WARN: Write to InfluxDB failed (remaining attempts: 3). { Error: getaddrinfo ENOTFOUND influxurl influxurl:433
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'hostname',
  host: 'host',
  port: 443 }

WARN: Write to InfluxDB failed (remaining attempts: 2). { Error: getaddrinfo ENOTFOUND influxurl influxurl:433
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'hostname',
  host: 'host',
  port: 443 }
```

Where would I be able to control this output and log say the code or errno?

**Comment by sranka** [comment]
The default retry mechanism always prints warning/errors, unless the `writeFailed` implements a custom retry mechanism (it has to return a promise in such a case). You can however

1. Register a custom logger to suppress warning messages on application startup
```js
const {setLogger, consoleLogger} = require('@influxdata/influxdb-client')
setLogger({
    warn: () => {},
    error: consoleLogger.error
})
```

2. change the writeFailed implementation to skip the default error log with the last attempt
```js
const MAX_RETRIES = 3
const writeOptions = {
  maxRetries: MAX_RETRIES,
  maxRetryDelay: 125000
  maxRetryTime: (125000+30000) * MAX_RETRIES
  writeFailed: function(error, lines, failedAttempts){
     // TODO use custom logging to inform about a failed retry
     if (failedAttempts === MAX_RETRIES) {
          // TODO persist protocol lines so that they can be possibly resent later using writeApi.writeRecords(lines)
          return Promise.resolve() // don't  let the library log the last failed attempt
     }
  },
}
```

The `writeOptions` above ensure that `options.maxRetryTime` is higher enough to execute all MAX_RETRIES attempts.

**Comment by sranka** [comment]
one last thing, the condition should be rather `if (failedAttempts === MAX_RETRIES+1)` to match overall count of write attempts

**Comment by pbegg** [comment]
This works perfectly - thanks for the help
